- name: destroy target groups
  elb_target_group:
    region: "{{ region }}"
    profile: "{{ profile | default(omit) }}"
    name: "{{ item.value }}"
    state: absent
  with_dict: "{{ target_groups }}"
